CREATE TABLE `frdas_test_0000`.`Untitled`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `comp_id` bigint(20) NOT NULL COMMENT '账户ID',
  `ply_type` int(5) NULL DEFAULT NULL COMMENT '策略类型0:分仓策略,1:物流策略,2:审核策略,3:订单自动备注策略;4:申报策略；5：第三方商品关联规则',
  `ply_name` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '策略名称',
  `ply_level` int(5) NULL DEFAULT NULL COMMENT '优先级',
  `condit_key` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '条件因子（key）,多个以‘,’隔开',
  `condit_expr` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '条件表达式',
  `condit_obj` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '条件对象',
  `wh_id` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `wh_name` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '仓库名称，多个以\',\'隔开',
  `logistics_id` bigint(20) NULL DEFAULT NULL COMMENT '物流公司',
  `logistics_wh_id` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '物流公司所属仓库',
  `logistics_wh_name` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '物流公司所属仓库名称',
  `is_stop` bit(1) NULL DEFAULT NULL COMMENT '是否停用',
  `created` datetime(0) NULL DEFAULT NULL COMMENT '创建日期',
  `modified` datetime(0) NULL DEFAULT NULL COMMENT '更新日期',
  `user_id` bigint(20) NULL DEFAULT NULL COMMENT '创建人',
  `is_sticker` bit(1) NULL DEFAULT NULL COMMENT '是否开启便签(目前只用于审核策略)',
  `sticker` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '便签内容(目前只用于审核策略)',
  `start_date` datetime(0) NULL DEFAULT NULL COMMENT '开始时间',
  `end_date` datetime(0) NULL DEFAULT NULL COMMENT '结束时间',
  `signature_type` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '签名方式',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_comp_id`(`comp_id`, `ply_type`, `ply_level`) USING BTREE,
  INDEX `auto_shard_key_comp_id`(`comp_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3700006 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '分仓物流审核策略表' ROW_FORMAT = Compact;